### ISSUE TITLE
Adding new tag

### ISSUE THREAD

**Issue by zhil** [KingCrunch/SSIBundle#4]
@KingCrunch 
Right now only master branch are compatible with latest symfony 2.8 / 3.0
It would be nice, if you will add new tag for it (v.0.3.0 ?) - its required by composer.

**Comment by KingCrunch** [comment]
See https://github.com/KingCrunch/SSIBundle/tree/v0.3.0

**Comment by zhil** [comment]
@kingcrunch great, thanks
